-- @module const.user_icons
local chevron = {
	Down = "",
	Right = "",
}

return {
	-- Duplicate chevron for LSP auto-complete
	chevron = {
		Down = chevron.Down,
		Right = chevron.Right,
	},
	diagnostics = {
		Error = "󰅚 ",
		Warn = "󰀪 ",
		Hint = "󰌶 ",
		Info = "󰋽 ",
	},
	kinds = {
		Array = "",
		Boolean = "󰨙",
		-- Boolean = "",
		Class = "",
		Codeium = "󰘦 ",
		Color = "",
		Control = "",
		Collapsed = chevron.Right,
		Constant = "",
		Constructor = "",
		Copilot = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "",
		File = "",
		Folder = "󰉋",
		Function = "",
		-- Function = "󰊕",
		Interface = "",
		Key = "",
		Keyword = "",
		Method = "",
		Module = "",
		Namespace = "",
		Null = "󰟢",
		Number = "",
		Object = "",
		Operator = "",
		Package = "",
		Property = "",
		Reference = "",
		-- Snippet = "",
		Snippet = "",
		String = "",
		-- String = "",
		-- String = "",
		Struct = "",
		Text = "",
		TypeParameter = "",
		Unit = "",
		Value = "",
		Variable = "",
	},
}
